### ISSUE TITLE
Fix copying to clipboard

### ISSUE THREAD

**Issue by qubes-user-837** [nil0x42/qubes-screenshooter#1]
Thanks for the cool project and very clear documentation. 

While trying to get it working, I noticed that it took screenshots and moved them into the target VM perfectly, but didn't copy them to the clipboard. I tried debugging the `qvm-run` command manually, but eventually found the issue on this line

> `my $remotepath = "$ENV{HOME}/QubesIncoming/dom0/${filename}";`

This should use `~` instead of `$ENV{HOME}`, as `$ENV{HOME}` evaluates to /home/[the dom0 username], but this doesn't necessarily exist in the target vm.

Example command that runs under qvm-run (typically with username "user"):
- `xclip -sel c -t image/png /home/qubes-user/QubesIncoming/dom0/screenshot.png`, vs
- `xclip -sel c -t image/png ~/QubesIncoming/dom0/screenshot.png`

With this change, it works. Hopefully this information can help others.

Command I used for testing
- `xclip -sel c -o | file -`

**Comment by nil0x42** [comment]
Thank you ! Fixed now
